apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: etcdclusters.etcd.database.coreos.com
spec:
  group: etcd.database.coreos.com
  versions:
  - name: v1beta2
    served: true
    storage: true
    schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                size:
                  type: integer
                pod:
                  type: object
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: etcdclusters
    # singular name to be used as an alias on the CLI and for display
    singular: etcdcluster
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: EtcdCluster
    listKind: EtcdClusterList
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - etcdclus
    - etcd