apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: ingester
  name: ingester
  namespace: monitoring
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      name: ingester
  serviceName: ingester
  template:
    metadata:
      labels:
        gossip_ring_member: "true"
        name: ingester
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: ingester
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -blocks-storage.gcs.bucket-name=blocks-bucket
        - -blocks-storage.tsdb.block-ranges-period=2h
        - -blocks-storage.tsdb.dir=/data/tsdb
        - -blocks-storage.tsdb.ship-interval=1m
        - -common.storage.backend=gcs
        - -distributor.health-check-ingesters=true
        - -ingester.max-global-metadata-per-metric=10
        - -ingester.max-global-metadata-per-user=30000
        - -ingester.max-global-series-per-user=150000
        - -ingester.ring.heartbeat-timeout=10m
        - -ingester.ring.num-tokens=512
        - -ingester.ring.prefix=
        - -ingester.ring.replication-factor=3
        - -ingester.ring.store=memberlist
        - -ingester.ring.tokens-file-path=/data/tokens
        - -ingester.ring.unregister-on-shutdown=true
        - -memberlist.bind-port=7946
        - -memberlist.join=dns+gossip-ring.monitoring.svc.cluster.local:7946
        - -runtime-config.file=/etc/mimir/overrides.yaml
        - -server.grpc-max-concurrent-streams=10000
        - -server.grpc.keepalive.min-time-between-pings=10s
        - -server.grpc.keepalive.ping-without-stream-allowed=true
        - -server.http-listen-port=8080
        - -target=ingester
        - -usage-stats.installation-mode=jsonnet
        image: grafana/mimir:2.6.0
        imagePullPolicy: IfNotPresent
        name: ingester
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 9095
          name: grpc
        - containerPort: 7946
          name: gossip-ring
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            memory: 25Gi
          requests:
            cpu: "4"
            memory: 15Gi
        volumeMounts:
        - mountPath: /data
          name: ingester-data
        - mountPath: /etc/mimir
          name: overrides
      nodeSelector:
        workload: mimir
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 1200
      volumes:
      - configMap:
          name: overrides
        name: overrides
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ingester-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: fast
