apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      name: memcached
  serviceName: memcached
  template:
    metadata:
      labels:
        name: memcached
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: memcached
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -m 6144
        - -I 1m
        - -c 16384
        - -v
        image: memcached:1.6.17-alpine
        imagePullPolicy: IfNotPresent
        name: memcached
        ports:
        - containerPort: 11211
          name: client
        resources:
          limits:
            memory: 9Gi
          requests:
            cpu: 500m
            memory: 6552Mi
      - args:
        - --memcached.address=localhost:11211
        - --web.listen-address=0.0.0.0:9150
        image: prom/memcached-exporter:v0.6.0
        imagePullPolicy: IfNotPresent
        name: exporter
        ports:
        - containerPort: 9150
          name: http-metrics
      nodeSelector:
        workload: mimir
  updateStrategy:
    type: RollingUpdate
