apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruler
  namespace: monitoring
spec:
  minReadySeconds: 10
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: ruler
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        gossip_ring_member: "true"
        name: ruler
    spec:
      containers:
      - args:
        - -blocks-storage.bucket-store.metadata-cache.backend=memcached
        - -blocks-storage.bucket-store.metadata-cache.memcached.addresses=dnssrvnoa+memcached-metadata.monitoring.svc.cluster.local:11211
        - -blocks-storage.bucket-store.metadata-cache.memcached.max-async-concurrency=50
        - -blocks-storage.bucket-store.metadata-cache.memcached.max-item-size=1048576
        - -blocks-storage.bucket-store.sync-dir=/data/tsdb
        - -blocks-storage.bucket-store.sync-interval=15m
        - -blocks-storage.gcs.bucket-name=blocks-bucket
        - -common.storage.backend=gcs
        - -distributor.health-check-ingesters=true
        - -ingester.ring.heartbeat-timeout=10m
        - -ingester.ring.prefix=
        - -ingester.ring.replication-factor=3
        - -ingester.ring.store=memberlist
        - -memberlist.bind-port=7946
        - -memberlist.join=dns+gossip-ring.monitoring.svc.cluster.local:7946
        - -querier.max-partial-query-length=768h
        - -ruler-storage.gcs.bucket-name=ruler-bucket
        - -ruler.alertmanager-url=http://alertmanager.monitoring.svc.cluster.local/alertmanager
        - -ruler.max-rule-groups-per-tenant=35
        - -ruler.max-rules-per-rule-group=20
        - -ruler.ring.store=memberlist
        - -ruler.rule-path=/rules
        - -runtime-config.file=/etc/mimir/overrides.yaml
        - -server.grpc.keepalive.min-time-between-pings=10s
        - -server.grpc.keepalive.ping-without-stream-allowed=true
        - -server.http-listen-port=8080
        - -store-gateway.sharding-ring.prefix=
        - -store-gateway.sharding-ring.replication-factor=3
        - -store-gateway.sharding-ring.store=memberlist
        - -target=ruler
        - -usage-stats.installation-mode=jsonnet
        image: grafana/mimir:2.6.0
        imagePullPolicy: IfNotPresent
        name: ruler
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 9095
          name: grpc
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "16"
            memory: 16Gi
          requests:
            cpu: "1"
            memory: 6Gi
        volumeMounts:
        - mountPath: /etc/mimir
          name: overrides
      nodeSelector:
        workload: mimir
      terminationGracePeriodSeconds: 600
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            name: ruler
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - configMap:
          name: overrides
        name: overrides
