apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-scheduler
  namespace: monitoring
spec:
  minReadySeconds: 10
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: query-scheduler
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: query-scheduler
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: query-scheduler
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -query-scheduler.max-outstanding-requests-per-tenant=100
        - -server.grpc.keepalive.min-time-between-pings=10s
        - -server.grpc.keepalive.ping-without-stream-allowed=true
        - -server.http-listen-port=8080
        - -target=query-scheduler
        - -usage-stats.installation-mode=jsonnet
        image: grafana/mimir:2.6.0
        imagePullPolicy: IfNotPresent
        name: query-scheduler
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 9095
          name: grpc
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 1Gi
        volumeMounts:
        - mountPath: /etc/mimir
          name: overrides
      nodeSelector:
        workload: mimir
      volumes:
      - configMap:
          name: overrides
        name: overrides
