apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: querier
  namespace: monitoring
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
          - periodSeconds: 60
            type: Percent
            value: 10
  maxReplicaCount: 40
  minReplicaCount: 10
  pollingInterval: 10
  scaleTargetRef:
    name: querier
  triggers:
  - metadata:
      metricName: cortex_querier_hpa_monitoring
      query: sum(max_over_time(cortex_query_scheduler_inflight_requests{container="query-scheduler",namespace="monitoring",quantile="0.75"}[5m]))
      serverAddress: http://prometheus.default:9090/prometheus
      threshold: "6"
    type: prometheus
