apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: distributor
  namespace: monitoring
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          policies:
          - periodSeconds: 60
            type: Percent
            value: 10
  maxReplicaCount: 40
  minReplicaCount: 10
  pollingInterval: 10
  scaleTargetRef:
    name: distributor
  triggers:
  - metadata:
      metricName: cortex_distributor_cpu_hpa_monitoring
      query: max_over_time(sum(rate(container_cpu_usage_seconds_total{container="distributor",namespace="monitoring"}[5m]))[15m:])
        * 1000
      serverAddress: http://prometheus.default:9090/prometheus
      threshold: "2000"
    type: prometheus
  - metadata:
      metricName: cortex_distributor_memory_hpa_monitoring
      query: max_over_time(sum(container_memory_working_set_bytes{container="distributor",namespace="monitoring"})[15m:])
      serverAddress: http://prometheus.default:9090/prometheus
      threshold: "2147483648"
    type: prometheus
