apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    name: store-gateway-pdb
  name: store-gateway-pdb
  namespace: monitoring
spec:
  maxUnavailable: 2
  selector:
    matchLabels:
      name: store-gateway
