apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    name: ingester-pdb
  name: ingester-pdb
  namespace: monitoring
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: ingester
