apiVersion: v1
kind: Service
metadata:
  labels:
    name: ruler
  name: ruler
  namespace: monitoring
spec:
  ports:
  - name: ruler-http-metrics
    port: 8080
    targetPort: 8080
  - name: ruler-grpc
    port: 9095
    targetPort: 9095
  selector:
    name: ruler
