apiVersion: v1
kind: Service
metadata:
  name: gossip-ring
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: gossip-ring
    port: 7946
    protocol: TCP
    targetPort: 7946
  selector:
    gossip_ring_member: "true"
