apiVersion: v1
kind: Service
metadata:
  labels:
    name: query-frontend
  name: query-frontend
  namespace: monitoring
spec:
  ports:
  - name: query-frontend-http-metrics
    port: 8080
    targetPort: 8080
  - name: query-frontend-grpc
    port: 9095
    targetPort: 9095
  selector:
    name: query-frontend
